runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /.*
  script: AustinEat.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
- name: ssl
  version: 2.7.11
# [END libraries]
